# Generated by Django 3.2.8 on 2023-06-23 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('venue', models.CharField(max_length=255)),
                ('theme', models.CharField(max_length=255)),
            ],
        ),
    ]
